### ISSUE TITLE
Please use library name same as library directory name 

### ISSUE THREAD

**Issue by ouoam** [ambiot/ambpro2_arduino#108]
From code

https://github.com/arduino/arduino-cli/blob/fe6d7499eb5e0920419829371c0e11f9af000499/legacy/builder/unused_compiled_libraries_remover.go#L42-L46

Arduino builder will remove directory not using by check from directory name and library name (from `library.properties`).
So, Arduino builder will remove compiled library and rebuild every time.

By change library name saves me 5 second every compile.
When I using `Watchdog, RTC, Multimedia, WiFi, Wire, Http, FileSystem`.

**Comment by M-ichae-l** [comment]
Hi @ouoam . The lib name is used to replace the default. For example, Ameba has its own WiFi lib which is  different from Arduino default. Therefore, to avoid conflicts and compile errors, same name WiFi will present to replace the default WiFi lib.

**Comment by ouoam** [comment]
HI @M-ichae-l . I think Arduino not have default lib.
ESP32 [lib](https://github.com/espressif/arduino-esp32/tree/master/libraries) can have library name WiFi and Wire without any compile errors.
Arduino AVR [lib](https://github.com/arduino/ArduinoCore-avr/tree/master/libraries), STM32 [lib](https://github.com/stm32duino/Arduino_Core_STM32/tree/main/libraries), ESP8266 [lib](https://github.com/esp8266/Arduino/tree/master/libraries) can also have library name Wire and SPI.

If you want to use AmebaWire name, can you change directory name to AmebaWire

**Comment by M-ichae-l** [comment]
https://github.com/arduino-libraries/WiFi

**Comment by ouoam** [comment]
From https://arduino.github.io/arduino-cli/0.27/sketch-build-process/#dependency-resolution
Ameba library must win https://github.com/arduino-libraries/WiFi in step 4
> A library that is architecture optimized wins against a library that is not architecture optimized (see [Architecture Matching](https://arduino.github.io/arduino-cli/0.27/sketch-build-process/#architecture-matching))

Or if pass step 4 can win in step 5
> A library that has a better "location priority" wins (see [Location Priority](https://arduino.github.io/arduino-cli/0.27/sketch-build-process/#location-priority))

With sub step 4
> The library is bundled with the board platform/core ([{runtime.platform.path}/libraries](https://arduino.github.io/arduino-cli/0.27/platform-specification/#global-predefined-properties))
---
This is example when I change ameba WiFi library name and have https://github.com/arduino-libraries/WiFi library
![image](https://github.com/ambiot/ambpro2_arduino/assets/12713801/3b5f0d05-2f7c-4c12-a6cf-2a2b4e33807a)

**Comment by M-ichae-l** [comment]
Hi @ouoam , 
The log above clearly shows that "Arduino" WiFi lib will replace by Ameba "WiFi" lib. 
Using same name will let IDE to processed to replace, that is Ameba SDK needs to do for avoiding conflicts.
