### ISSUE TITLE
Inquiry about changing wifi udp video streaming buffer

### ISSUE THREAD

**Issue by qkrwogur** [ambiot/ambpro2_arduino#146]
I am streaming video in real time using Wi-Fi UDP. 
There is a phenomenon in which the video stops while the log below continues to be displayed. 
Please let me know if I can fix the udp buffer or what exactly this log means.

[Driver]: skb_unavailable=15 in last 2 seconds

**Comment by S10143806H** [comment]
Hi @qkrwogur ,

This log is used as a dynamic check_timer handler in WiFi core functions. It will be set during the mlme (Media Access Control (MAC) Sublayer Management Entity) init stage and will be triggered when skb packet fails to be transmitted. 

While `skb` is a control structure used for sending and receiving data packets. Some fields point to allocated memory to store the packets. When transferring to the protocol stack, the pointer is moved to obtain information such as Ethernet header, network header, transport header, and so on.

Thanks
