### ISSUE TITLE
FaceMask Detection

### ISSUE THREAD

**Issue by rkuo2000** [ambiot/ambpro2_arduino#154]
[Facemask dataset](https://www.kaggle.com/datasets/ashishjangra27/face-mask-12k-images-dataset) are 96x96 pictures, I have trained a CNN model file at [kaggle.com/code/rkuo2000/facemask-cnn](https://www.kaggle.com/code/rkuo2000/facemask-cnn/)

still need to run MTCNN or FaceDetection with camera's image, 
then crop the face and resize into 96x96 for detection.

Is it possible to modify these from your FaceDetection example ?
Or should I directly go for training YOLOv7 with facemask data ?

**Comment by M-ichae-l** [comment]
Currently AMB82-mini only supports following models, 
![image](https://github.com/ambiot/ambpro2_arduino/assets/35476432/7000a9e1-e7ae-4d41-b69d-b83b606fe7cc)

**Comment by rkuo2000** [comment]
Thanks.

**Comment by M-ichae-l** [comment]
Yolov7-tiny .pt online transfer is supported now. [https://www.amebaiot.com/en/amebapro2-ai-convert-model/](https://www.amebaiot.com/en/amebapro2-ai-convert-model/)
Closed as issue resolved.
