### ISSUE TITLE
Palm Print Identification

### ISSUE THREAD

**Issue by rkuo2000** [ambiot/ambpro2_arduino#155]
I would like to use AMB82-MINI to do Palm Print Identification, 
1) need to detect palm, and crop the palm
2) need more image processing to get finger-print (filtering, crop the palm, convert the size)
3) using Palm Print model to train, then predict
Any suggestion of developing this Palm Print Identification !!!

**Comment by M-ichae-l** [comment]
To achieve your application currently there is 1 way, 

- You can trained the object detection model of yolov3-tiny, yolov4-tiny, or yolov7-tiny. Then applied into AMB82-mini.

**Comment by rkuo2000** [comment]
How much memory left for loading another NN model ? 
After Hand is detected by yolov7-tiny, 
how to switch to the next NN model for palm-print comparison ?

**Comment by M-ichae-l** [comment]
Current max NN model size is 9MB. 
[Customized AI model Installation Guide](https://www.amebaiot.com/en/amebapro2-apply-ai-model-docs/)

**Comment by M-ichae-l** [comment]
close as no further issue.
