### ISSUE TITLE
多塊 AMB82 MINI RTSPFaceRecognition 共享特徵值

### ISSUE THREAD

**Issue by YiJunKo** [ambiot/ambpro2_arduino#162]
目前想要多個 AMB82 MINI 在不同的地點做人臉辨識，想請問有沒有辦法可以做到多個 AMB82 MINI 共享特徵值?
或是能不能請求新增新功能

**Comment by M-ichae-l** [comment]
@YiJunKo 
從API做修改直接 把“特徵值”/“識別的人臉data”送到cloud， 然後在發給另一個AMB82mini處理

AMB82-mini是邊緣計算， 處理data是不需要聯網的。多塊 AMB82 MINI RTSPFaceRecognition 都是相對獨立， 如果要共享，就需要上面提到的思路，使用者來設計開發application。

**Comment by YiJunKo** [comment]
@M-ichae-l 感謝您的回覆！
我有想過把“特徵值”/“識別的人臉data”改存在SD卡中，但目前找不到“特徵值”/“識別的人臉data”的變數存放在哪部分，想請問這兩個值存放位置在哪邊？謝謝！

**Comment by YiJunKo** [comment]
@M-ichae-l Hi, if you have answer, answer me , please!

**Comment by M-ichae-l** [comment]
@YiJunKo 
There is a new feature is going to added into the SDK. 
- Store the AI/NN model into the SD card.

**Comment by M-ichae-l** [comment]
Add **Store the AI/NN model into the SD card.** by #213
