### ISSUE TITLE
I2C Err when running MPU6050_DMP_Teapot.ino

### ISSUE THREAD

**Issue by rkuo2000** [ambiot/ambpro2_arduino#166]
sample code: 

[I2C  Err]terminate tx op. after error

[I2C  Err]residual len: 1

[I2C  Err]last dat: 68

[I2C  Err]tx abrt src:00000001

[I2C  Err]terminate tx op. after error

[I2C  Err]residual len: 2

[I2C  Err]last dat: 68

[I2C  Err]tx abrt src:00000001

[I2C  Err]terminate tx op. after error

[I2C  Err]residual len: 1

[I2C  Err]last dat: 68

[I2C  Err]tx abrt src:00000001

[I2C  Err]terminate tx op. after error

[I2C  Err]residual len: 1

[I2C  Err]last dat: 68

D
[I2C  Err]tx abrt src:00000001

[I2C  Err]terminate tx op. after error

[I2C  Err]residual len: 3

[I2C  Err]last dat: 68

MP Initialization failed (code 1)
Sample Rate: 100

**Comment by M-ichae-l** [comment]
@rkuo2000 
This SDK does not support MPU6050 yet.

**Comment by M-ichae-l** [comment]
@rkuo2000 
MPU6050 is supported by latest early release version 4.0.7

**Comment by rkuo2000** [comment]
I confirmed MPU6050_raw & MPU6050_DMP6 were verified, MPU6050 is supported.
