### ISSUE TITLE
MPU6050_raw.ino [ERROR] requestFrom: readed=1, quantity=14 

### ISSUE THREAD

**Issue by rkuo2000** [ambiot/ambpro2_arduino#168]
Library: MPU6050 by Electronic Cats
MPU6050.h patch with #include <avr/dtostrf.h>

50,232,20713,4345,-7903,-4353
50,232,20713,4345,-7903,-4353

[ERROR] requestFrom: readed=1, quantity=14 

47,-16159,-14109,8193,4071,22749
47,-16159,-14109,8193,4071,22749

[ERROR] requestFrom: readed=1, quantity=14 

61,-18197,-18208,8440,20475,-4369
61,-18197,-18208,8440,20475,-4369

**Comment by rkuo2000** [comment]
char *dtostrf (double val, signed char width, unsigned char prec, char *sout);

add the above code should fix compilation error of missing to include <avr/dtostrf.h>

**Comment by M-ichae-l** [comment]
MPU6050 is supported by latest early release version 4.0.7

**Comment by rkuo2000** [comment]
Yes, V4.0.7 build 20240329 has fixed this error. Thanks !
