### ISSUE TITLE
AudioNN + ObjDet 

### ISSUE THREAD

**Issue by rkuo2000** [ambiot/ambpro2_arduino#171]
example code: [AudioObjectDetection.ino](https://github.com/rkuo2000/Arduino/blob/master/examples/AMB82-MINI/AudioObjectDetection/AudioObjectDetection.ino)

Compiled : OK
Problem : it still runs as an Object Detection, code size is same as object detection, audio classification is not included.
Questions:
1) how can I fix my code to bring in Audio Classification ?
2) how do I retrain audioNN to be a smaller one ? can I just have a few audio item to be recognized ? 
(hello, talking, yelling, slapping, snapping finger)

**Comment by pammyleong** [comment]
Hi @rkuo2000,

To be able to run Audio NN and Object Detection together, you have to combine both of the examples. I have combined the code (please refer to the attached zip folder), but I have not tried it. However, as the YAMNet model is big, it is impossible to run these 2 models together on the board. 

You will get this error " Sketch too big; see https://support.arduino.cc/hc/en-us/articles/360013825179 for tips on reducing it.
text section exceeds available space in board" 

To note: modelSelect function in the code is used to select NN task and the model used. Therefore, you need to call this function to be able to upload the neccessary model into the board.

Hence, you have to retrain the YAMNet model to reduce the size. You may refer to https://github.com/tensorflow/models/tree/master/research/audioset/yamnet.

[ObjDetAudioNN.zip](https://github.com/ambiot/ambpro2_arduino/files/13683555/ObjDetAudioNN.zip)

**Comment by pammyleong** [comment]
Loading NN model using SD card feature is up. You can give it a try.

You may refer to this YouTube video for tutorial: https://www.youtube.com/watch?v=cVvdnXiCAa4

Below is the updated code.
[ObjectDetectionAudioClassification.zip](https://github.com/ambiot/ambpro2_arduino/files/14751136/ObjectDetectionAudioClassification.zip)
