### ISSUE TITLE
EmotionDetectionNN

### ISSUE THREAD

**Issue by rkuo2000** [ambiot/ambpro2_arduino#172]
Based on RTSPFaceDetection.ino,
how do I create the following add into FDPostProcess ?

img = CV2.crop(frame)
img = CV2.rgb2gray(img)
img = CV2.resize(img, (48, 48))
emo = NNemotiondetection.predict(img)
my emotion detection model is trained by
[kaggle.com/rkuo2000/fer2013](https://www.kaggle.com/code/rkuo2000/fer2013-cnn)

[Pretrained README](https://github.com/rkuo2000/EdgeAI-course/blob/main/pretrained/README.md)
file : [fer2013_cnn.h5](https://github.com/rkuo2000/EdgeAI-course/blob/main/pretrained/emotion_detection/fer2013_cnn.h5) (1.26MB)
total params = 103,143
input_shape = (48,48,1)
test accuracy = 54.89% (model size is minimized, so accuracy is reduced ! )

**Comment by M-ichae-l** [comment]
RTSPFaceDetection is based of mobilefacener and scrfd model not CNN. refer to [common_nn_models](https://github.com/ambiot/ambpro2_arduino/tree/dev/Arduino_package/ameba_pro2_nn_models/common_nn_models)
