### ISSUE TITLE
rtp video stream

### ISSUE THREAD

**Issue by qkrwogur** [ambiot/ambpro2_arduino#176]
I want to transmit video via RTP, not RTSP. 
rtp_control()
rtp_create()
rtp_destroy()
rtp_handle()
I want to use a function, but I want to know how to use it.

**Comment by M-ichae-l** [comment]
https://www.amebaiot.com/en/rtl8735b-arduino-api-rtp/

**Comment by qkrwogur** [comment]
Is there a way to transmit video via RTP without using RTSP??

**Comment by ambiot** [comment]
@qkrwogur 
For current RTP API it is only supports audio streaming.

**Comment by M-ichae-l** [comment]
closed as no further discussion
