### ISSUE TITLE
[Error] AmebaPro2 directory only allow 1 SDK!!! Please check again.

### ISSUE THREAD

**Issue by Oliver0804** [ambiot/ambpro2_arduino#179]
Problem:
Compilation failure
![截圖 2023-12-21 下午3 56 03](https://github.com/ambiot/ambpro2_arduino/assets/8245980/cfc47083-3e2f-4423-a625-7bcd8b9d70e1)

Environment description:
Arduino IDE version 1.8.19 https://raw.githubusercontent.com/ambiot/ambpro2_arduino/dev/Arduino_package/package_realtek_amebapro2_early_index.json

I have tried reinstalling, but some data might be stored in other cache locations in Windows.
Can you help provide information on which paths this program checks so that I can manually delete them?

**Comment by pammyleong** [comment]
Hi @Oliver0804, please ensure that your AmebaPro2 folder only contains one SDK folder. C:\Users\{USERNAME}\AppData\Local\Arduino15\packages\realtek\hardware\AmebaPro2
![image](https://github.com/ambiot/ambpro2_arduino/assets/43200418/98da1165-285a-4fd0-b6d0-b98135958a11)

**Comment by Oliver0804** [comment]
![截圖 2023-12-29 下午1 42 39](https://github.com/ambiot/ambpro2_arduino/assets/8245980/33f700f0-aa07-4823-94a9-a9b200076e26)
Thank you. Indeed, there are two folders present. 
I'm not sure what might have happened, 
but it's clear that installing both Arduino 1.0 and 2.0 on my computer at the same time might have led to this situation
