### ISSUE TITLE
Compatibility Issues and Error Messages When Installing Development Versions in Different Arduino IDEs

### ISSUE THREAD

**Issue by Oliver0804** [ambiot/ambpro2_arduino#180]
When installing using the same path https://github.com/ambiot/ambpro2_arduino/raw/dev/Arduino_package/package_realtek_amebapro2_early_index.json, the 4.0.6 development version can be seen in Arduino IDE version 1.0, but it's not visible in Arduino IDE 2.0. Also, when installing other development versions in Arduino 2.0, there are occasions where a 404 error message appears.

![截圖 2023-12-21 下午3 31 29](https://github.com/ambiot/ambpro2_arduino/assets/8245980/f2d9f97d-200f-41ff-9e3c-39253c3325a0)
![截圖 2023-12-21 下午3 32 27](https://github.com/ambiot/ambpro2_arduino/assets/8245980/5fc2763d-ae71-467c-bcc7-c2ad79bdea86)

**Comment by pammyleong** [comment]
Hi @Oliver0804,

I tried on Arduino IDE 2.2.0 and 2.0.0, and the path works fine for me. May I know which IDE version you are using now?
We have changed the link to remove ".com" as the latest IDE version doesn't allow ".com" in the path.

Maybe you can try the old link if you are using the older version:
Old: https://github.com/ambiot/ambpro2_arduino/raw/main/Arduino_package/package_realtek.com_amebapro2_index.json
New: https://github.com/ambiot/ambpro2_arduino/raw/main/Arduino_package/package_realtek_amebapro2_index.json

Else, you can also try deleting the .json file in Arduino15 folder and it will be installed again when you open Arduino IDE and input the path in Preference. 
![image](https://github.com/ambiot/ambpro2_arduino/assets/43200418/0b3ba3bc-cd9a-436a-a3fc-6484daeb0e7b)

**Comment by M-ichae-l** [comment]
`404 server issue. 
`
Looks like anything wrong with your internet? or GitHub server issue.

**Comment by M-ichae-l** [comment]
Close as there is no further issue.
