### ISSUE TITLE
VL53L0X running with Error message

### ISSUE THREAD

**Issue by rkuo2000** [ambiot/ambpro2_arduino#183]
Arduino Library: https://github.com/pololu/vl53l0x-arduino
Arduino Example Code: https://github.com/rkuo2000/Arduino/blob/master/examples/Sensors/VL53L0X/VL53L0X.ino

Finished Compilation and Running :

[ERROR] requestFrom: readed=1, quantity=1 
[ERROR] requestFrom: readed=1, quantity=1 
[ERROR] requestFrom: readed=1, quantity=1 
[ERROR] requestFrom: readed=2, quantity=2 
256 mm

**Comment by Oliver0804** [comment]
I recommend using an I2C scanner first to confirm that the Ameba has correctly identified the VL53L0X through I2C.

**Comment by geofrancis** [comment]
support have confirmed that the i2c wont work with Arduino libraries but they never explained what the issue was.

**Comment by Oliver0804** [comment]
> support have confirmed that the i2c wont work with Arduino libraries but they never explained what the issue was.

They have provided an answer https://github.com/ambiot/ambpro2_arduino/issues/136 , but the revised version has not yet been included in the official release.

**Comment by rkuo2000** [comment]
> I recommend using an I2C scanner first to confirm that the Ameba has correctly identified the VL53L0X through I2C.

It found too many devices @@ there is only VL53L0X

I2C Scanner
Scanning...
I2C device found at address 0x01  !
I2C device found at address 0x02  !

**Comment by Oliver0804** [comment]
> > I recommend using an I2C scanner first to confirm that the Ameba has correctly identified the VL53L0X through I2C.
> 
> It found too many devices 0x01~0x7E @@ there is only VL53L0X
> 
> I2C Scanner Scanning... I2C device found at address 0x01 ! I2C device found at address 0x02 !

This indicates that I2C is not working properly. https://github.com/ambiot/ambpro2_arduino/issues/136
Im waiting for fix the feature and merge it into the official release.

**Comment by M-ichae-l** [comment]
VL53L0X is added at #230

**Comment by M-ichae-l** [comment]
close as no further discussion

**Comment by geofrancis** [comment]
Is the amb82 compatible with generic arduino i2c now?
