### ISSUE TITLE
Can an electronic zoom function be added to achieve automatic focus and autofocus based on some depth of field data?

### ISSUE THREAD

**Issue by Tomi-ren** [ambiot/ambpro2_arduino#186]
I really hope you can evaluate this feature and look forward to it being implemented. Hold your hands!

**Comment by Tomi-ren** [comment]
keep-alive

**Comment by M-ichae-l** [comment]
@Tomi-ren 
Thanks to point is out. 
Currently, the camera module is fixed lens and HW limits that it is unable to do automatic focus.

**Comment by Tomi-ren** [comment]
I have updated the lens hardware and added lenses that can focus and zoom. I wonder if there is an API interface based on image analysis that can obtain focus judgment, so that I can easily control the motor closed-loop on the focusing and zoom lens. If it cannot be achieved, I speculate that the optical path calculation can be based on the focus and zoom, and a formula can be designed in the control program to achieve open-loop zoom and focusing functions.

**Comment by Tomi-ren** [comment]
keep-alive

**Comment by M-ichae-l** [comment]
For AMb82-mini the camera module is fixed as JFX37, [datasheet](https://www.amebaiot.com/en/datasheet-download-amb82-mini/). It is possible to change the len for some functions like [IR functions](https://forum.amebaiot.com/t/removing-lens-of-amb86-mini-to-remove-ir-filter-and-placing-an-ir-cut-filter/2599/3).
But for automatic focus, if it requires api update or driver update that is not going to process currently.

**Comment by M-ichae-l** [comment]
Close for no further issue
