### ISSUE TITLE
The link in document 2.1 is the failure.

### ISSUE THREAD

**Issue by Oliver0804** [ambiot/ambpro2_arduino#29]
https://github.com/ambiot/ambpro2_arduino/raw/master/Arduino_package/package_realtek.com_amebapro2_index.json
suggest to remove temporarily or describe more

**Comment by M-ichae-l** [comment]
Updated by 5ceb5cbc377a939788492806eee6dcf8ea74a672
Please use the following link for development, 
https://github.com/ambiot/ambpro2_arduino/raw/dev/Arduino_package/package_realtek.com_amebapro2_early_index.json

**Comment by Oliver0804** [comment]
I understand,
But I think the same thing happened to other people..ha
