### ISSUE TITLE
Ethernet TCP Examples

### ISSUE THREAD

**Issue by ajsb85** [ambiot/ambpro2_arduino#74]
Dearest.

Could you implement the TCP examples using the Ethernet HAL API?

https://www.amebaiot.com/en/amebapro2-amb82-mini-arduino-server-client/

It is very important for our roadmap.

Thank you in advance.

Reference:

[ambpro2_sdk/component/mbed/targets/hal/rtl8735b/ethernet_api.c](https://github.com/ambiot/ambpro2_sdk/blob/main/component/mbed/targets/hal/rtl8735b/ethernet_api.c#L3)

**Comment by S10143806H** [comment]
Dear @ajsb85 ,

Thank you for raising this issue and supporting Ameba Pro2 in your roadmap. 
We will get back to you again upon internal discussion.

Thanks.

**Comment by S10143806H** [comment]
Hi @ajsb85 ,

So far there is no Ethernet hardware interface on the AMB82-MINI evaluation board. 
After talking about it, we won't be able to support the ethernet feature yet. 

Thanks

**Comment by M-ichae-l** [comment]
Closed as AMB82 mini did not support the Ethernet. It is hardware limitation.

**Comment by TeaBear5** [comment]
> Closed as AMB82 mini did not support the Ethernet. It is hardware limitation.

We are using the AMB82 mini as a prototype device and would like to support ethernet to the RTL8735B chip when we move to our own board using the chip.  It appears that the underlying chip does in fact have support for the ethernet phy if my understanding is correct?

The picture below is taken from the datasheet.

![image](https://github.com/user-attachments/assets/d3e9b9c3-3dd7-4bf9-9d9d-be7c84a13699)

Will we be able to support this setup as suggested below?

![image (10)](https://github.com/user-attachments/assets/bd930452-046a-45c7-b3e6-808b5ba3a112)

Is there firmware in this repo to support this already?  Additionally if there isn't, is it something that is possible?
