### ISSUE TITLE
如何在AMB82-Mini 實現套用你的客製化模型?不確定怎麼上傳檔案才可以獲得官方郵寄的nb檔?

### ISSUE THREAD

**Issue by 3b012178** [ambiot/ambpro2_arduino#93]
我們都知道amb82-mini 可以使用yolo-v7-tiny
官網也提供 如何套用你的客製化模型 的網址 
但是裡面網址詳細說了需要以下資料
{
上傳包含cfg文件和權重文件的zip文件（必填，請上傳包含“.cfg”和“.weights”文件的文件夾或壓縮文件，均為英文命名，限制：35MB）
}
但是我訓練好的yolo v7 tiny 的
{weight資料夾 含有best.pt檔}
{cfg資料夾 含有yolov7-tiny.yaml檔}

請問我該怎麼做 怎麼上傳 才可以確保資料都對?可以順利上傳到官網 獲得nb檔呢?

**Comment by michellethemaker** [comment]
請看我們的[FAQ](https://forum.amebaiot.com/t/amb82-mini/1812)或相關的[FB post](https://www.facebook.com/groups/AmebaIoT/posts/3383282478593231/?comment_id=3385575445030601&reply_comment_id=3389329377988541)！

**Comment by M-ichae-l** [comment]
@3b012178 
hi， 目前的客製化模型， 只有針對darknet的， yolo v7 tiny 的pytorch還沒有支援。

**Comment by 3b012178** [comment]
了解 那想請問 可是AMB82-mini 可以跑yolov7-tiny,nb檔執行物件偵測 但卻不能用yolov7-tiny  訓練跑自己的訓練檔  >請問有甚麼差嗎?

**Comment by M-ichae-l** [comment]
可以用yolov7-tiny 訓練跑自己的訓練檔， 但是要用darknet訓練。

**Comment by 3b012178** [comment]
方便使用FB交流嗎?我想要更近一步了解

**Comment by M-ichae-l** [comment]
https://github.com/WongKinYiu/yolov7
yolov7-tiny 的訓練請去上面的鏈接諮詢。
