### ISSUE TITLE
AMB82 MINI RTSPFaceRecognition

### ISSUE THREAD

**Issue by TAH-MIS** [ambiot/ambpro2_arduino#99]
麻煩新增加功能 
能於 Arduino 程式裡可以移除某一已不需要偵測的人臉
而非 RESET 清除所有的人臉 再將需要的臉加入REG
以節省 Flash memory 能更多紀錄人臉
還有 能於某一 AMB82 MINI 偵測到的人臉 能夠有方法將 特徵值 Copy 到另一 AMB82 MINI 
公司內會有需要多個 AMB82 MINI 但如果每個都重新記錄會花很多時間

**Comment by M-ichae-l** [comment]
@TAH-MIS  這個功能會加入未來的更新計劃。 還請耐心等待。

**Comment by M-ichae-l** [comment]
[Pre Release Version 4.0.5 Pre-release](https://github.com/ambiot/ambpro2_arduino/releases/tag/V4.0.5-QC-V01)

> 能於 Arduino 程式裡可以移除某一已不需要偵測的人臉

新功能已經添加

**Comment by YiJunKo** [comment]
@TAH-MIS @M-ichae-l 
您們好,我想請問一下關於 "AMB82 MINI 偵測到的人臉 能夠有方法將 特徵值 Copy 到另一 AMB82 MINI，公司內會有需要多個 AMB82 MINI 但如果每個都重新記錄會花很多時間"，這個功能已經有被新增或是有解決辦法了嗎？
